### ISSUE TITLE
ARM_BEETLE_SOC: flash download failed in uvision5

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/oob-mbed-os-example-ble#10]
Command used:
mbed export -i uvision5 -m ARM_BEETLE_SOC

Open the project, compiled successfully but got flash download failure:

Load "C:\\my\\dev\\mbed_5_0\\oob_520\\oob-mbed-os-example-ble\\BLE_HeartRate\\.build\\uvision5\\BLE_HeartRate.axf" 
No Algorithm found for: 00000000H - 0000FFFFH
No Algorithm found for: 00010000H - 0001FFFFH
No Algorithm found for: 00020000H - 0002003BH
Erase skipped!
Error: Flash Download failed  -  "Cortex-M3"
Flash Load finished at 11:32:20

**Comment by 0xc0170** [comment]
I could not locate it in the platform page, but I know that this platform requires additional pack for uvision. here are details: https://community.arm.com/docs/DOC-11699

@fvincenzo @screamerbg Shall we add somewhere or is it already, how to debug beetle in uvision (requirements to fetch new pack) ? I could not locate it at https://developer.mbed.org/platforms/ARM-IoTEP-Beetle/

**Comment by sunsmilearm** [comment]
@0xc0170 Thanks. I will test this.

**Comment by sunsmilearm** [comment]
@0xc0170 The exported project works.
