### ISSUE TITLE
Documentation: folder .build should be BUILD

### ISSUE THREAD

**Issue by terhei** [ARMmbed/oob-mbed-os-example-ble#12]
In documentation:

> mbed cli creates a BIN or an HEX file in a .build/<target-name>/<toolchain> directory under the example's directory. 

For me, **BUILD** folder was created instead of **.build**

**Comment by pan-** [comment]
@terhei Could you provide more background ? setup, command, etc ?

**Comment by terhei** [comment]
Setup:
Windows 7
mbed cli version 0.9.7

Followed "To build an example:" instructions from https://github.com/ARMmbed/oob-mbed-os-example-ble

**Comment by pan-** [comment]
@terhei Thanks for the details, this has been changed by `mbed-cli`. 
I've open a PR to fix that issue : https://github.com/ARMmbed/oob-mbed-os-example-ble/pull/14. Could you review it ?
