### ISSUE TITLE
ARCH_PRO: Link error in exported IAR project [RC3]

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-ble#17]
### Step to reproduce

```
mbed import https://github.com/ARMmbed/oob-mbed-os-example-ble
```
* Add "ARCH_PRO" target into BLE_BatteryLevel\mbed_app.json

```
cd BLE_BatteryLevel
mbed export -m ARCH_PRO -t IAR
```

* Double click the ```BLE_BatteryLevel.eww```
* Make the progject

### Error detail
```
Changed settings forces a full rebuild... 
Building configuration: BLE_BatteryLevel - BLE_BatteryLevel 
Updating build tree... 

(snip)

Linking 
Error[Lp011]: section placement failed 
            unable to allocate space for sections/blocks with a total estimated minimum size of 0x80d4 bytes (max align 0x8) in <[0x100000c8-0x10007fdf]> (total  
uncommitted space 0x7f18). 
Error while running Linker 
 
Total number of errors: 1 
Total number of warnings: 416 
```

Completed log file is [here](https://github.com/ARMmbed/oob-mbed-os-example-ble/files/532377/oob-rc3-iar-link-error.txt).

### Toolchain version
IAR Embedded Workbench for ARM v7.70.1.11486
IAR Embedded Workbench shared components v7.5.1.4405

progen --version
0.9.10

progendef --version
0.2.33

**Comment by bridadan** [comment]
I guess the size is too big! We haven't really tested this combination of board and example before. @pan- any suggestions? Maybe this just isn't a supported configuration for this release?

**Comment by pan-** [comment]
Yes, there is not enough RAM on the ARCH PRO board to embed everything. 
It is not the case when the application is compiled with mbed-cli. 
Their should be something wrong with IAR exporters.

@0xc0170 Any idea ?

**Comment by 0xc0170** [comment]
> Their should be something wrong with IAR exporters.

IAR exporter should produce the same output, if it's not a case, we got a bug. @toyowata Can you compare those 2 please?

**Comment by pan-** [comment]
>  Can you compare those 2 please?

`mbed-cli` generate an executable when it use IAR. EW doesn't because their is a failure during the link. That's the issue.

If they are supposed to produce the same output then the simple fact that one is able to generate a binary and the other doesn't indicates a bug in the IAR exporter.

**Comment by toyowata** [comment]
@0xc0170 @pan- 

After the long battle with map files and build log files between IAR command-line and EWARM IDE, I finally found two issues here.

### Destroy static objects

In the EWARM project (generated by mbed export -m ARMCH_PRO -i IAR), the ```Destroy static objects``` was enabled, IAR command-line build was not.

![ewarm_cpp_options](https://cloud.githubusercontent.com/assets/4926755/19508848/7aa19f00-9616-11e6-86ce-d9c098f9449a.png)

It makes extra ```.iar.dynexit``` section (rw data) in EWARM build which consumes 0x1c8 additional data and also extra 0x768 code in .text sections for this example code.  

https://www.iar.com/support/tech-notes/linker/what-is-linker-created-and-lcgbwk-in-the-.map-file/

This made final image size bigger and I got link error.  Disabling this option saved more memory space and I did not get link error at all.

### Wrong pre-define macros

In the EWARM project, there are some unnecessary pre-define macros for K64F target even ARCH_PRO (NXP LPC1768 target, Cortex-M3) build.  This should not be in the exported project.

![ewarm_pp_defines](https://cloud.githubusercontent.com/assets/4926755/19508857/831d6b28-9616-11e6-8006-61d424f1c1b7.png)

**Comment by 0xc0170** [comment]
> Wrong pre-define macros

The macros should be resolved soon (there's PR on mbed-os to fix that)

> Destroy static objects

There's a new template update PR on mbed-os, I'll check if this is disabled there, thanks for sharing

**Comment by bridadan** [comment]
Awesome analysis @toyowata !

**Comment by 0xc0170** [comment]
@theotherjimmy We might want to disable destroy static objects in the IAR template, I tested latest master, it's still enabled in the template.

**Comment by 0xc0170** [comment]
The macros for K64F that should not be there as reported above should be fixed in RC4.

**Comment by MarceloSalazar** [comment]
Partially fixed. Suggest not to test in RC4.

The 5.2.x release should have this properly fixed.
