### ISSUE TITLE
ARM_BEETLE_SOC: online IDE error

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/oob-mbed-os-example-ble#21]
error message:

```
Error: Identifier "e" is undefined in "extras/BLE_URIBeacon/mbed-os.lib/events/equeue/equeue.c", Line: 105, Col: 50
Error: Expected an expression in "extras/BLE_URIBeacon/mbed-os.lib/events/equeue/equeue.c", Line: 134, Col: 11
Error: Identifier "p" is undefined in "extras/BLE_URIBeacon/mbed-os.lib/events/equeue/equeue.c", Line: 134, Col: 50
Error: Expected an expression in "extras/BLE_URIBeacon/mbed-os.lib/events/equeue/equeue.c", Line: 333, Col: 15
Error: Identifier "e" is undefined in "extras/BLE_URIBeacon/mbed-os.lib/events/equeue/equeue.c", Line: 333, Col: 44
Info: Unable to download. Fix the reported errors...

```

**Comment by MarceloSalazar** [comment]
@sunsmilearm how are you importing this example into the Online IDE? (there are multiple folders with main.cpp files)

@screamerbg Do you think we could enable the Online IDE to support importing a particular folder?
e.g. https://github.com/ARMmbed/oob-mbed-os-example-ble/tree/master/BLE_BatteryLevel

**Comment by MarceloSalazar** [comment]
Discussed internally. There is no easy fix for this release.
The workaround is to delete other folders as commented in https://github.com/ARMmbed/oob-mbed-os-example-tls/issues/26#issuecomment-254755562

The solution is to split the examples into multiple github repos.
Conversations to start after the 5.2 release @pan-

**Comment by pan-** [comment]
> The solution is to split the examples into multiple github repos.

Why ? The examples are automatically mirrored in separate repository on developer.mbed.org which is the entry point to these examples. The solution would have been to do the same for this repo during the OOB phase.
