### ISSUE TITLE
nRF52: HRM export MAKE_GCC doesn't work

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/oob-mbed-os-example-ble#22]
App: HRM ARMmbed/oob-mbed-os-example-ble @ mbed-os-5.2.0-rc4

Builds fine, but after flashing the LED is not blinking and nothing detected in the "nRF Connect".

**Comment by pan-** [comment]
@bulislaw Did you burn the `-combined.hex` file ? 
It is explained in the readme: 

> Note: Depending on the build process, the file which has to be flashed on a Nordic target can also be named <module_name>-combined.hex. If <module_name>-combined.hex and <module_name>.hex are present in the build directory, flash `-combined.hex.

**Comment by bulislaw** [comment]
Rigth, it works with the ```BLE_HeartRate-combined.hex```. I understand it's documented, but it's confusing and not consistent with what we usually do (we were talking a lot about consistency recently) -> any chance of adding extra step to rename the ``` BLE_HeartRate-combined.hex``` to ``` BLE_HeartRate.hex```?

**Comment by pan-** [comment]
It is already tracked: https://github.com/ARMmbed/mbed-os/issues/3105

**Comment by bulislaw** [comment]
Perfect, closing.
