### ISSUE TITLE
NUCLEO_F429ZI: HRM compilation fails for mbed cli and make_gcc_arm

### ISSUE THREAD

**Issue by bulislaw** [ARMmbed/oob-mbed-os-example-ble#23]
App: HRM ARMmbed/oob-mbed-os-example-ble @ mbed-os-5.2.0-rc4

```
$ mbed compile -t GCC_ARM -m NUCLEO_F429ZI
[...]
../source/main.cpp:19:21: fatal error: ble/BLE.h: No such file or directory
```

**Comment by toyowata** [comment]
@bulislaw You need to put the target configuration for NUCLEO_F429ZI in you mbed_app.json.

```
        "NUCLEO_F429ZI": {
            "target.features_add": ["BLE"],
            "target.extra_labels_add": ["ST_BLUENRG"],
            "target.macros_add": ["IDB0XA1_D13_PATCH"]
        },
```

https://github.com/ARMmbed/oob-mbed-os-example-ble/#using-st-nucleo-shield-on-other-targets

**Comment by pan-** [comment]
I'm closing this.

**Comment by bulislaw** [comment]
Why don't we have that by default for the boards that require it? The mbed_app.json is per app only so it won't influence any other usecases.

**Comment by pan-** [comment]
>Why don't we have that by default for the boards that require it? 

It would require to test it against 40+ boards for all the examples (8) and all compilers (3) then debug it. Arduino connector implementation might be inconsistent from board to board (see the `IDB0XA1_D13_PATCH` macro which should be define case by case...). 

I'm not sure that would be the best use of my time to support these 960 combinations. 

> The mbed_app.json is per app only so it won't influence any other usecases.

As soon as other BLE shields will be available, for sure it will influence other use case!

**Comment by bulislaw** [comment]
Fair enough.
