### ISSUE TITLE
ARM_BEETLE_SOC: link error in GCC_ARM

### ISSUE THREAD

**Issue by sunsmilearm** [ARMmbed/oob-mbed-os-example-ble#9]
Commands:
>mbed compile -m ARM_BEETLE_SOC -t GCC_ARM

Error:
Link: BLE_HeartRate
c:/program files (x86)/gnu tools arm embedded/4.8 2014q3/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld.exe:./mbed-os/targets/TARGET_ARM_SSG/TARGET_BEETLE/devi
ce/TOOLCHAIN_GCC_ARM/BEETLE.ld:169: syntax error
collect2.exe: error: ld returned 1 exit status
[ERROR] c:/program files (x86)/gnu tools arm embedded/4.8 2014q3/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld.exe:./mbed-os/targets/TARGET_ARM_SSG/TARGET_BEE
TLE/device/TOOLCHAIN_GCC_ARM/BEETLE.ld:169: syntax error
collect2.exe: error: ld returned 1 exit status

**Comment by pan-** [comment]
@sunsmilearm It is burried in the documentation of mbed CLI but you should use GCC v 4.9.x series: https://docs.mbed.com/docs/mbed-os-handbook/en/5.1/dev_tools/cli/

> If you want to use the GCC ARM Embedded toolchain, set GCC_ARM_PATH to the binary directory of your GCC ARM installation (example: C:\Program Files\GNU Tools ARM Embedded\4.9 2015q2\bin). Use versions 4.9 of GCC ARM Embedded; version 5.0 or any version above might be incompatible with the tools.

**Comment by sunsmilearm** [comment]
@pan- Thanks. I will verify this.

**Comment by sunsmilearm** [comment]
@pan- No errors using GCC 4.9

**Comment by 0xc0170** [comment]
@sunsmilearm I am closing this. If there's anything left, please reopen.
